# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24492b8a6dbdcd9e582a06345e6d0b571f8dc937f6700bf394769dbd8f4e1feab62286b05758ee5b502802c5e0aa16d9eb9a5f0d7fee9a78610e2f141bdbcbb7

test:
  secret_key_base: 147726b51a199c7d6eb8d7e7794e800b3b869fbe1457ab071119a3134d6c40b138dba657b9db94f6c322d8afd2aa1aeca326de3a161cece4a029fec46334838c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
